intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.
#import impl_libs += libhello%lib{hello}

lib{pugixml}: {hxx ixx txx cxx}{** -version} hxx{version} $impl_libs $intf_libs

# Include the generated version header into the distribution (so that we don't
# pick up an installed one) and don't remove it when cleaning in src (so that
# clean results in a state identical to distributed).
#
hxx{version}: in{version} $src_root/manifest
{
  dist  = true
  clean = ($src_root != $out_root)
}

# Build options.
#
cxx.poptions =+ "-I$out_root" "-I$src_root"

obja{*}: cxx.poptions += -DPUGIXML_STATIC_BUILD
objs{*}: cxx.poptions += -DPUGIXML_SHARED_BUILD

if($cxx.class == "msvc" || ($cxx.id == "clang" && $cxx.target.class == "windows"))
{
  objs{*}: cxx.poptions += '-DPUGIXML_API=__declspec(dllexport)'
}

# Export options.
#
lib{pugixml}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_root"
  cxx.export.libs = $intf_libs
}

liba{pugixml}: cxx.export.poptions += -DPUGIXML_STATIC
libs{pugixml}: cxx.export.poptions += -DPUGIXML_SHARED

if($cxx.class == "msvc" || ($cxx.id == "clang" && $cxx.target.class == "windows"))
{
  objs{*}: cxx.export.poptions += '-DPUGIXML_API=__declspec(dllimport)'
}

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version. See the version module
# for details on the version.* variable values.
#
if $version.pre_release
  lib{pugixml}: bin.lib.version = @"-$version.project_id"
else
  lib{pugixml}: bin.lib.version = @"-$version.major.$version.minor"

# Install into the pugixml/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/pugixml/
  install.subdirs = true
}
